export default {
  container: {
    maxWidth: '60rem',
  },
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  border: {
    radius: '0.4rem',
  },
  button: {
    small: 'padding: 15px 40px',
    medium: 'padding: 15px 40px',
    large: 'padding: 15px 60px',
    relative: 'padding: 12px 35px',
    borderRadius: '30px   ',
  },
  layers: {
    background: 0,
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  font: {
    family:
      'MaisonNeue, NibPro, MaisonNeueExtended, MaisonNeueBook, MaisonNeueExtendedBook, MaisonNeueExtended, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
    sizes: {
      xxsmall: '12px',
      xsmall: '14px',
      small: '16px',
      medium: '18px',
      large: '20px',
      xlarge: '22px',
      xxlarge: '25px',
      xxxlarge: '30px',
      larger: '33px',
      largest: '55px',
      huge: '60px',
    },
    height: {
      xxsmall: '12px',
      xsmall: '14px',
      small: '20px',
      medium: '22px',
      large: '24px',
      xlarge: '26px',
      xxlarge: '28px',
      xxxlarge: '34px',
      larger: '33px',
      largest: '55px',
      huge: '65px',
    },
    colors: {
      primary: '#4D4D4D',
      secondary: '#7FA2CB',
      button: '#E6E6E6',
      white: '#FFFFF',
    },
    fontFamily: {
      primary: 'MaisonNeue',
      secondary: 'NibPro',
      MaisonNeueExtendedBook: 'MaisonNeueExtendedBook',
      MaisonNeueBook: 'MaisonNeueBook',
      MaisonNeueExtended: 'MaisonNeueExtended',
      NibPro: 'MaisonNeueBook',
    }
  },
  colors: {
    primary: '#7FA2CB',
    primaryHover: '#7FA2CB',
    secondary: '#7FA2CB',
    mainBg: '#E6E6E6',
    boxBg: '#FAFAFA',
    texts: '#030517',
    white: '#FFFFFF',
    black: '#121212',
    gray: '#cfcfcf',
    darkGray: '#7FA2CB',
    footer: '#4D4D4D',
  },
  spacings: {
    xxsmall: '5px',
    xsmall: '10px',
    small: '15px',
    medium: '20px',
    large: '40px',
    xlarge: '60px',
    xxlarge: '70px',
  },
};